### ISSUE TITLE
This project appears to be broken

### ISSUE THREAD

**Issue by tsneidin** [banool/recreation-gov-campsite-checker#26]
2020-11-23 13:23:25,596 - 1710 - DEBUG - Querying for 231927 with these params: {'start_date': '2020-05-01T00:00:00.000Z'}
Something went wrong
2020-11-23 13:23:25,918 - 1710 - ERROR - Something went wrong
Traceback (most recent call last):
  File "camping.py", line 257, in <module>
    code = 0 if main(parks) else 1
  File "camping.py", line 158, in main
    park_id, args.start_date, args.end_date, args.campsite_type
  File "camping.py", line 89, in get_park_information
    resp = send_request(url, params)
  File "camping.py", line 50, in send_request
    resp.status_code, url, resp.text
RuntimeError: ('failedRequest', 'ERROR, 400 code received from https://www.recreation.gov/api/camps/availability/campground/231927/month?: {"error":"Please select a date within the next two years."}\n')

**Comment by tsneidin** [comment]
Nevermind, user error;^)
