### ISSUE TITLE
User agent code broken

### ISSUE THREAD

**Issue by CodingGrom** [banool/recreation-gov-campsite-checker#52]
Hi, so I've had great success with this code in the past (around two months ago was my last successful use). Upon trying to use it again, though, I'm getting a strange error (that re-installing didn't fix):

When I run the command `python3 camping.py --start-date 2022-12-10 --end-date 2022-12-25 --parks 232448 232450 232447 232449`

I get back:

```
recreation-gov-campsite-checker-master % python3 camping.py --start-date 2022-12-10 --end-date 2022-12-15 --parks 232448 232450 232447 232449
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/opt/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/anaconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/anaconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/recreation-gov-campsite-checker-master/camping.py", line 13, in <module>
    from clients.recreation_client import RecreationClient
  File "/recreation-gov-campsite-checker-master/clients/recreation_client.py", line 11, in <module>
    class RecreationClient:
  File "/recreation-gov-campsite-checker-master/clients/recreation_client.py", line 19, in RecreationClient
    headers = {"User-Agent": UserAgent().random}
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/fake.py", line 75, in load
    self.data = load_cached(
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 187, in load
    ret = json.loads(get(
  File "/recreation-gov-campsite-checker-master/myvenv/lib/python3.9/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

Has anyone else had this error? And if so, do you know how to fix it? Thanks so much!

**Comment by brianmacy** [comment]
```
diff --git a/clients/recreation_client.py b/clients/recreation_client.py
index 02cd882..7f563dc 100644
--- a/clients/recreation_client.py
+++ b/clients/recreation_client.py
@@ -1,7 +1,7 @@
 import logging

 import requests
-from fake_useragent import UserAgent
+import user_agent

 from utils import formatter

@@ -16,7 +16,7 @@ class RecreationClient:
     )
     MAIN_PAGE_ENDPOINT = BASE_URL + "/api/camps/campgrounds/{park_id}"

-    headers = {"User-Agent": UserAgent().random}
+    headers = {"User-Agent": user_agent.generate_user_agent() }

     @classmethod
     def get_availability(cls, park_id, month_date):
diff --git a/requirements.txt b/requirements.txt
index 7969f5e..a5327aa 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -17,3 +17,4 @@ six==1.15.0
 soupsieve==1.8
 toml==0.10.0
 urllib3==1.24.2
+user_agent
```

**Comment by CodingGrom** [comment]
Hi @brianmacy, thanks a ton! Sorry to bug, where should I replace these lines?

Thanks again!

**Comment by brianmacy** [comment]
You'll need to ask the author to apply them if you aren't familiar with code or code diffs.

**Comment by CodingGrom** [comment]
I figured it out, thanks!

**Comment by banool** [comment]
I'll reopen this since I'd like to fix it on my side. I won't have time to fix this myself any time soon though, so if someone wants to open a PR that'd be great. Thanks for reporting this!

**Comment by CodingGrom** [comment]
Just wanted to note here, since this error occurred for me again (not using updates since my original comment), that the following line fixes things for me:

`pip install --upgrade fake-useragent`
