### ISSUE TITLE
Twitter Notifcations not working

### ISSUE THREAD

**Issue by morenone** [banool/recreation-gov-campsite-checker#63]
python camping.py --start-date 2024-07-19 --end-date 2024-07-21 --parks 233911 | python notifier.py @my_twitter_handle

Here's my output from the above command:

Traceback (most recent call last):
  File "/mnt/raid/git/recreation-gov-campsite-checker/notifier.py", line 102, in <module>
    main(sys.argv, sys.stdin)
  File "/mnt/raid/git/recreation-gov-campsite-checker/notifier.py", line 69, in main
    _create_tweet(tweet, tc)
  File "/mnt/raid/git/recreation-gov-campsite-checker/notifier.py", line 27, in _create_tweet
    resp = api.PostUpdate(tweet)
  File "/mnt/raid/git/recreation-gov-campsite-checker/myvenv/lib/python3.10/site-packages/twitter/api.py", line 1177, in PostUpdate
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/mnt/raid/git/recreation-gov-campsite-checker/myvenv/lib/python3.10/site-packages/twitter/api.py", line 4908, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/mnt/raid/git/recreation-gov-campsite-checker/myvenv/lib/python3.10/site-packages/twitter/api.py", line 4928, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{'message': 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product', 'code': 453}]
(myvenv) root@shawn-UCSC-C220-M5SX:/mnt/raid/git/recreation-gov-campsite-checker#

**Comment by banool** [comment]
Hey there, open to PRs to fix this if this is a code issue, though judging by the error perhaps the key doesn't have appropriate permissions.
